# Generated by Django 2.0.6 on 2019-07-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField(blank=True, null=True)),
                ('employer_name', models.TextField(blank=True, null=True)),
                ('stature', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('age', models.TextField(blank=True, null=True)),
                ('born', models.TextField(blank=True, null=True)),
                ('jobname', models.TextField(blank=True, null=True)),
                ('salary', models.TextField(blank=True, null=True)),
                ('hope_location', models.TextField(blank=True, null=True)),
                ('native_place', models.TextField(blank=True, null=True)),
                ('certificate', models.TextField(blank=True, null=True)),
                ('school', models.TextField(blank=True, null=True)),
                ('profession', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('now_location', models.TextField(blank=True, null=True)),
                ('nationality', models.TextField(blank=True, null=True)),
                ('politics_status', models.TextField(blank=True, null=True)),
                ('job_status', models.TextField(blank=True, null=True)),
                ('hope_industry', models.TextField(blank=True, null=True)),
                ('hope_position', models.TextField(blank=True, null=True)),
                ('job_category', models.TextField(blank=True, null=True)),
                ('marital_status', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, null=True)),
                ('usertel', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TZpgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField(blank=True, null=True)),
                ('employer_name', models.TextField(blank=True, null=True)),
                ('stature', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('age', models.TextField(blank=True, null=True)),
                ('born', models.TextField(blank=True, null=True)),
                ('jobname', models.TextField(blank=True, null=True)),
                ('salary', models.TextField(blank=True, null=True)),
                ('hope_location', models.TextField(blank=True, null=True)),
                ('native_place', models.TextField(blank=True, null=True)),
                ('certificate', models.TextField(blank=True, null=True)),
                ('school', models.TextField(blank=True, null=True)),
                ('profession', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('now_location', models.TextField(blank=True, null=True)),
                ('nationality', models.TextField(blank=True, null=True)),
                ('politics_status', models.TextField(blank=True, null=True)),
                ('job_status', models.TextField(blank=True, null=True)),
                ('hope_industry', models.TextField(blank=True, null=True)),
                ('hope_position', models.TextField(blank=True, null=True)),
                ('job_category', models.TextField(blank=True, null=True)),
                ('marital_status', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_zpgg',
                'managed': False,
            },
        ),
    ]
