# Generated by Django 2.0.6 on 2019-07-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baizhiapp', '0002_daynumber_userip_visitnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='IP地址')),
                ('count', models.IntegerField(default=0, verbose_name='访问次数')),
                ('country', models.CharField(max_length=30, verbose_name='所在国家')),
                ('location', models.CharField(max_length=30, verbose_name='地区')),
                ('province', models.CharField(max_length=30, verbose_name='省份')),
                ('city', models.CharField(max_length=30, verbose_name='城市')),
                ('operator', models.CharField(max_length=30, verbose_name='所属运营商')),
            ],
            options={
                'verbose_name': '访问用户信息',
                'verbose_name_plural': '访问用户信息',
            },
        ),
    ]
